### ISSUE TITLE
Tables do not render

### ISSUE THREAD

**Issue by Benjamin-Philip** [starbelly/rebar3_ex_doc#47]
For example, let a module have docs like this:

```html
%%  ...
%%
%% <table border="1">
%%  <tr>
%%      <td>Letter</td>
%%      <td>Number</td>
%%  </tr>
%%  <tr>
%%      <td>A</td>
%%      <td>1</td>
%%  </tr>
%%  <tr>
%%      <td>B</td>
%%      <td>2</td>
%%  </tr>
%%  <tr>
%%      <td>C</td>
%%      <td>3</td>
%%  </tr>
%% </table>
%%
%%  ...
```

In order to represent the following data:

|Letter|Number|
|---------|------------|
|A|1|
|B|2|
|C|3|

This table is incorrectly rendered with ExDoc because the table html has been omitted:

`doc/MODULE.html`:

```html
<p>... </p>LetterNumberA1B2C3<p> ... </p>
```

This table is correctly rendered by EDoc:

`doc/MODULE.html`:

```html
  <table border="1">
   <tr>
       <td>Letter</td>
       <td>Number</td>
   </tr>
   <tr>
       <td>A</td>
       <td>1</td>
   </tr>
   <tr>
       <td>B</td>
       <td>2</td>
   </tr>
   <tr>
       <td>C</td>
       <td>3</td>
   </tr>
  </table>
```

**Comment by starbelly** [comment]
Hi @Benjamin-Philip , 

The issue here is lack of support with `shell_docs` in erlang right now. We can see the supported list of tags via : 

```
1> shell_docs:supported_tags().
[a,p,'div',br,h1,h2,h3,h4,h5,h6,i,b,em,strong,pre,code,ul,
 ol,li,dl,dt,dd]
 ``` 
 
 While edoc, does have support for tables (but quite picky about what is valid and invalid), these elements will not end up in doc chunks. If that's correct I believe a PR to OTP would be required to support this functionality, and perhaps a PR to ex_doc itself as well. 
 
Here is a relevant discussion which has a wealth of information : https://erlangforums.com/t/rebar3-ex-doc-overview-usage-documention-feedback/2325/11?u=starbelly

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, do you think we'll be able to deal with this limitation in the scope of `rebar3_ex_doc`? If not I'd close the issue. Otherwise lemme know your thoughts on the matter.

**Comment by Benjamin-Philip** [comment]
@paulo-ferraz-oliveira, as you pointed out, there is [a push to move to markdown or asciidoc](https://github.com/erlef/build-and-packaging-wg/issues/60) for documentation. Although the timeline for the change is unknown, I don't think it is worth our time and effort to add support for tables if EDoc as a whole will be replaced by something else.

I seem to be the only person who's needed tables up to this point. I personally don't mind waiting 2 years for tables (via a better documentation format). We could always add it if others need it until Erlang shifts to md or asciidoc.

I think the best course of action is to close this issue.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks.
